// Code generated by bpf2go; DO NOT EDIT.
//go:build mips || mips64 || ppc64 || s390x

package loader

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type probeEvent struct {
	_           structs.HostLayout
	TimestampNs uint64
	Pid         uint32
	Ppid        uint32
	Uid         uint32
	Mode        uint32
	ExitCode    uint32
	Dport       uint16
	Family      uint16
	Type        uint8
	Daddr       [16]uint8
	Comm        [16]uint8
	Filename    [256]uint8
	Cgroup      [128]uint8
	_           [7]byte
}

// Names of all BPF objects in the ELF.
//
// Used for safe lookups in a Collection or CollectionSpec.
const (
	probeMapEvents           = "events"
	probeProgHandleChmod     = "handle_chmod"
	probeProgHandleConnect   = "handle_connect"
	probeProgHandleExec      = "handle_exec"
	probeProgHandleExit      = "handle_exit"
	probeProgHandleFchmodat  = "handle_fchmodat"
	probeProgHandleFchmodat2 = "handle_fchmodat2"
	probeProgHandleOpen      = "handle_open"
	probeProgHandleOpenat    = "handle_openat"
	probeProgHandleOpenat2   = "handle_openat2"
	probeVarCgroupMode       = "cgroup_mode"
	probeVarUnused           = "unused"
)

// loadProbe returns the embedded CollectionSpec for probe.
func loadProbe() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_ProbeBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load probe: %w", err)
	}

	return spec, err
}

// loadProbeObjects loads probe and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*probeObjects
//	*probePrograms
//	*probeMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadProbeObjects(obj any, opts *ebpf.CollectionOptions) error {
	spec, err := loadProbe()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// probeSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type probeSpecs struct {
	probeProgramSpecs
	probeMapSpecs
	probeVariableSpecs
}

// probeProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type probeProgramSpecs struct {
	HandleChmod     *ebpf.ProgramSpec `ebpf:"handle_chmod"`
	HandleConnect   *ebpf.ProgramSpec `ebpf:"handle_connect"`
	HandleExec      *ebpf.ProgramSpec `ebpf:"handle_exec"`
	HandleExit      *ebpf.ProgramSpec `ebpf:"handle_exit"`
	HandleFchmodat  *ebpf.ProgramSpec `ebpf:"handle_fchmodat"`
	HandleFchmodat2 *ebpf.ProgramSpec `ebpf:"handle_fchmodat2"`
	HandleOpen      *ebpf.ProgramSpec `ebpf:"handle_open"`
	HandleOpenat    *ebpf.ProgramSpec `ebpf:"handle_openat"`
	HandleOpenat2   *ebpf.ProgramSpec `ebpf:"handle_openat2"`
}

// probeMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type probeMapSpecs struct {
	Events *ebpf.MapSpec `ebpf:"events"`
}

// probeVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type probeVariableSpecs struct {
	CgroupMode *ebpf.VariableSpec `ebpf:"cgroup_mode"`
	Unused     *ebpf.VariableSpec `ebpf:"unused"`
}

// probeObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadProbeObjects or ebpf.CollectionSpec.LoadAndAssign.
type probeObjects struct {
	probePrograms
	probeMaps
	probeVariables
}

func (o *probeObjects) Close() error {
	return _ProbeClose(
		&o.probePrograms,
		&o.probeMaps,
	)
}

// probeMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadProbeObjects or ebpf.CollectionSpec.LoadAndAssign.
type probeMaps struct {
	Events *ebpf.Map `ebpf:"events"`
}

func (m *probeMaps) Close() error {
	return _ProbeClose(
		m.Events,
	)
}

// probeVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadProbeObjects or ebpf.CollectionSpec.LoadAndAssign.
type probeVariables struct {
	CgroupMode *ebpf.Variable `ebpf:"cgroup_mode"`
	Unused     *ebpf.Variable `ebpf:"unused"`
}

// probePrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadProbeObjects or ebpf.CollectionSpec.LoadAndAssign.
type probePrograms struct {
	HandleChmod     *ebpf.Program `ebpf:"handle_chmod"`
	HandleConnect   *ebpf.Program `ebpf:"handle_connect"`
	HandleExec      *ebpf.Program `ebpf:"handle_exec"`
	HandleExit      *ebpf.Program `ebpf:"handle_exit"`
	HandleFchmodat  *ebpf.Program `ebpf:"handle_fchmodat"`
	HandleFchmodat2 *ebpf.Program `ebpf:"handle_fchmodat2"`
	HandleOpen      *ebpf.Program `ebpf:"handle_open"`
	HandleOpenat    *ebpf.Program `ebpf:"handle_openat"`
	HandleOpenat2   *ebpf.Program `ebpf:"handle_openat2"`
}

func (p *probePrograms) Close() error {
	return _ProbeClose(
		p.HandleChmod,
		p.HandleConnect,
		p.HandleExec,
		p.HandleExit,
		p.HandleFchmodat,
		p.HandleFchmodat2,
		p.HandleOpen,
		p.HandleOpenat,
		p.HandleOpenat2,
	)
}

func _ProbeClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed probe_bpfeb.o
var _ProbeBytes []byte
